import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';

type Position = { spendable:number; daily_available:number; essential_daily_target:number; days_to_cover:number; reservations:number };
type Category = { name:string; color:string; amount:number; percentage:number; count:number };
type Trend = { date:string; label:string; amount:number };
type Recent = { id:number; description:string; category:string; color:string; amount:number; occurred_on:string; purchase_nature:string };
type Metrics = { cycle:{start:string;end:string;days_remaining:number;budget:number;remaining:number;used_percentage:number;over_budget:number}; month_total:number; previous_month_total:number; month_change_percentage:number|null; today_total:number; daily_average:number; impulsive_total:number; impulsive_rate:number; essential_total:number; transaction_count:number; no_spend_days:number; largest_expense?:{description:string;amount:number;category:string;occurred_on:string}; categories:Category[]; trend:Trend[]; recent_expenses:Recent[] };
const money = (value:number) => new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(value)+' FCFA';
const natureLabel:Record<string,string> = { planned:'Prévue', unplanned_necessary:'Nécessaire', impulsive:'Impulsive' };

function TrendChart({ data }:{data:Trend[]}) {
    const max = Math.max(...data.map(item=>item.amount),1);
    return <div><div className="flex h-48 items-end gap-1" aria-label="Dépenses des 30 derniers jours">{data.map((item,index)=><div key={item.date} className="group relative flex h-full flex-1 items-end"><div className={`w-full rounded-t-sm transition ${item.amount ? 'bg-[#8d73cf] group-hover:bg-[#6d4cc7]' : 'bg-[#ece8f2]'}`} style={{height:`${Math.max(item.amount/max*100,item.amount?4:1)}%`}} /><div className="pointer-events-none absolute bottom-full left-1/2 z-10 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded-lg bg-[#302b45] px-2 py-1 text-[11px] text-white group-hover:block">{item.label} · {money(item.amount)}</div>{index%7===0&&<span className="absolute -bottom-6 left-0 text-[10px] text-[#9a96a7]">{item.label}</span>}</div>)}</div><div className="mt-8 flex items-center justify-between text-xs text-[#9a96a7]"><span>Il y a 30 jours</span><span>Aujourd’hui</span></div></div>;
}

function CategoryChart({ categories,total }:{categories:Category[];total:number}) {
    let cursor=0; const gradient=categories.length?categories.map(category=>{const start=cursor;cursor+=category.percentage;return `${category.color} ${start}% ${cursor}%`;}).join(', '):'#ece8f2 0 100%';
    return <div className="grid items-center gap-6 sm:grid-cols-[180px_1fr]"><div className="relative mx-auto h-44 w-44 rounded-full" style={{background:`conic-gradient(${gradient})`}}><div className="absolute inset-7 flex flex-col items-center justify-center rounded-full bg-white text-center"><span className="text-xs text-[#8b8699]">Ce mois</span><strong className="mt-1 text-lg">{money(total)}</strong></div></div><div className="space-y-3">{categories.length?categories.map(category=><div key={category.name}><div className="flex items-center justify-between gap-3 text-sm"><span className="flex min-w-0 items-center gap-2"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{backgroundColor:category.color}}/><span className="truncate">{category.name}</span></span><strong>{category.percentage}%</strong></div><div className="mt-1 flex justify-between pl-[18px] text-xs text-[#9a96a7]"><span>{category.count} achat(s)</span><span>{money(category.amount)}</span></div></div>):<p className="text-sm text-[#8b8699]">Aucune dépense ce mois-ci.</p>}</div></div>;
}

export default function Dashboard({position,metrics}:{position:Position;metrics:Metrics}) {
    const change=metrics.month_change_percentage;
    const improving=change!==null&&change<=0;
    return <AuthenticatedLayout header={<div><p className="mm-eyebrow">Cycle du {new Date(metrics.cycle.start).toLocaleDateString('fr-FR')} au {new Date(metrics.cycle.end).toLocaleDateString('fr-FR')}</p><h2 className="mt-1 text-xl font-semibold text-[#302b45]">Mes dépenses</h2></div>}><Head title="Tableau de bord" />
        <main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
            <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
                <article className="mm-card p-5"><p className="text-sm text-[#746f86]">Dépensé ce cycle</p><p className="mt-2 text-3xl font-semibold tracking-tight">{money(metrics.month_total)}</p><p className={`mt-3 text-xs font-semibold ${change===null?'text-[#9a96a7]':improving?'text-emerald-700':'text-rose-600'}`}>{change===null?'Pas encore de comparaison':`${change>0?'+':''}${change}% par rapport au cycle précédent`}</p></article>
                <article className="mm-card p-5"><p className="text-sm text-[#746f86]">Moyenne par jour</p><p className="mt-2 text-3xl font-semibold tracking-tight">{money(metrics.daily_average)}</p><p className="mt-3 text-xs text-[#9a96a7]">{metrics.transaction_count} dépense(s) enregistrée(s)</p></article>
                <article className="mm-card p-5"><p className="text-sm text-[#746f86]">Achats impulsifs</p><p className="mt-2 text-3xl font-semibold tracking-tight text-rose-600">{metrics.impulsive_rate}%</p><p className="mt-3 text-xs text-[#9a96a7]">{money(metrics.impulsive_total)} ce mois-ci</p></article>
                <article className="mm-card p-5"><p className="text-sm text-[#746f86]">Jours sans dépense</p><p className="mt-2 text-3xl font-semibold tracking-tight text-emerald-700">{metrics.no_spend_days}</p><p className="mt-3 text-xs text-[#9a96a7]">Aujourd’hui : {money(metrics.today_total)}</p></article>
            </section>

            <section className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><article className="mm-card p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="mm-eyebrow">Évolution</p><h3 className="mt-1 text-xl font-semibold">Dépenses sur 30 jours</h3></div><p className="text-sm text-[#746f86]">Repère les pics et les périodes calmes</p></div><div className="mt-7"><TrendChart data={metrics.trend}/></div></article><article className="mm-card p-6"><p className="mm-eyebrow">Répartition</p><h3 className="mt-1 text-xl font-semibold">Où part mon argent ?</h3><div className="mt-6"><CategoryChart categories={metrics.categories} total={metrics.month_total}/></div></article></section>

            <section className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><article className="mm-card p-6"><div className="flex items-center justify-between"><div><p className="mm-eyebrow">Activité récente</p><h3 className="mt-1 text-xl font-semibold">Dernières dépenses</h3></div><Link href={route('expenses.index')} className="text-sm font-semibold text-[#6d4cc7]">Tout voir</Link></div><div className="mt-5 divide-y divide-[#eeeaf3]">{metrics.recent_expenses.length?metrics.recent_expenses.map(expense=><div key={expense.id} className="flex items-center justify-between gap-4 py-3"><div className="flex min-w-0 items-center gap-3"><span className="h-9 w-1.5 shrink-0 rounded-full" style={{backgroundColor:expense.color}}/><div className="min-w-0"><p className="truncate font-semibold">{expense.description}</p><p className="truncate text-xs text-[#8b8699]">{expense.category} · {natureLabel[expense.purchase_nature]||'Non précisée'} · {new Date(expense.occurred_on).toLocaleDateString('fr-FR')}</p></div></div><strong className="shrink-0 text-rose-600">−{money(expense.amount)}</strong></div>):<div className="py-10 text-center text-sm text-[#8b8699]">Ajoute ta première dépense pour démarrer le suivi.</div>}</div></article>
                <div className="space-y-4"><article className="rounded-[1.25rem] border border-[#ddd4f1] bg-[#eee9f8] p-6"><p className="mm-eyebrow">Disponible réel</p><p className="mt-2 text-3xl font-semibold">{money(position.spendable)}</p><p className="mt-2 text-sm leading-6 text-[#746f86]">Soit {money(position.daily_available)} par jour pendant {position.days_to_cover} jours.</p><div className="mt-5 flex gap-2"><Link href={route('expenses.index')} className="rounded-xl bg-[#6d4cc7] px-4 py-2.5 text-sm font-semibold text-white">Ajouter</Link><Link href={route('projects.index')} className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-[#5a3da9]">Simuler</Link></div></article>{metrics.largest_expense&&<article className="mm-card p-5"><p className="text-sm text-[#746f86]">Plus grosse dépense du mois</p><p className="mt-2 truncate font-semibold">{metrics.largest_expense.description}</p><p className="mt-1 text-2xl font-semibold text-rose-600">{money(metrics.largest_expense.amount)}</p><p className="mt-1 text-xs text-[#9a96a7]">{metrics.largest_expense.category}</p></article>}</div></section>
            <section className="mm-card overflow-hidden p-6 sm:p-7"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mm-eyebrow">Budget principal du cycle</p><p className="mt-2 text-3xl font-semibold text-[#302b45]">{money(metrics.cycle.remaining)} <span className="text-base font-medium text-[#8b8699]">restants sur {money(metrics.cycle.budget)}</span></p><p className="mt-2 text-sm text-[#746f86]">Encore {metrics.cycle.days_remaining} jour(s) jusqu’au prochain cycle.</p></div><div className="text-left sm:text-right"><strong className="text-2xl text-[#6d4cc7]">{metrics.cycle.used_percentage}%</strong><p className="text-xs text-[#8b8699]">du budget consommé</p></div></div><div className="mt-5 h-2.5 overflow-hidden rounded-full bg-[#eeeaf3]"><div className={`h-full rounded-full ${metrics.cycle.used_percentage >= 90 ? 'bg-rose-500' : metrics.cycle.used_percentage >= 70 ? 'bg-amber-500' : 'bg-[#7b5dcc]'}`} style={{width:`${metrics.cycle.used_percentage}%`}} /></div>{metrics.cycle.over_budget > 0 && <p className="mt-3 text-sm font-semibold text-rose-600">Budget dépassé de {money(metrics.cycle.over_budget)}</p>}</section>
        </main>
    </AuthenticatedLayout>;
}
