import ApplicationLogo from '@/Components/ApplicationLogo';
import InputError from '@/Components/InputError';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router, useForm, usePage } from '@inertiajs/react';
import { FormEvent } from 'react';

type Connection = { chat_id:string; telegram_username?:string; is_active:boolean; verified_at?:string; last_update_at?:string; webhook_url:string; notification_preferences?:{daily_summary?:boolean;decision_alerts?:boolean} };
type Message = { id:number; direction:'incoming'|'outgoing'; kind:string; text?:string; imported:boolean; sent_at?:string };
const kindLabel:Record<string,string> = { behavior_alert:'Alerte Nikolaii', daily_summary:'Résumé quotidien', notification:'Notification', message:'Message' };

export default function Telegram({connection,messages}:{connection:Connection|null;messages:Message[]}) {
    const flash=usePage().props.flash as {success?:string}|undefined;
    const form=useForm({bot_token:'',chat_id:connection?.chat_id||'',telegram_username:connection?.telegram_username||''});
    const preferences=useForm({daily_summary:connection?.notification_preferences?.daily_summary??true,decision_alerts:connection?.notification_preferences?.decision_alerts??true});
    const submit=(event:FormEvent)=>{event.preventDefault();form.post(route('telegram.store'),{preserveScroll:true,onSuccess:()=>form.reset('bot_token')});};

    return <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-[#302b45]">Assistant Telegram</h2>}><Head title="Telegram" />
        <main className="mx-auto max-w-6xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
            {flash?.success&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm font-medium text-emerald-800">{flash.success}</div>}
            <section className="mm-card flex flex-col justify-between gap-6 overflow-hidden p-6 sm:flex-row sm:items-center sm:p-7">
                <div className="flex items-start gap-4"><ApplicationLogo className="h-14 w-14 shrink-0"/><div><p className="mm-eyebrow">Nikolaii · ton garde-fou</p><h1 className="mt-1 text-2xl font-semibold text-[#302b45]">Ton budget te parle dans Telegram</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#746f86]">Ajoute une dépense, simule un projet et reçois des alertes adaptées à ton cycle, sans notifications inutiles.</p></div></div>
                <span className={`w-fit rounded-full px-3 py-1.5 text-xs font-semibold ${connection?.verified_at?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>{connection?.verified_at?'● Bot actif':'○ À connecter'}</span>
            </section>

            <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]">
                <section className="mm-card h-fit p-6">
                    <h2 className="text-lg font-semibold">{connection?'Configuration':'Connecter mon bot'}</h2><p className="mt-1 text-sm text-[#8b8699]">Le jeton est chiffré et ne réapparaît jamais à l’écran.</p>
                    <form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm font-semibold">Jeton BotFather<input type="password" className="mt-1 w-full rounded-xl border-slate-300" value={form.data.bot_token} onChange={e=>form.setData('bot_token',e.target.value)} placeholder="123456:ABC…"/></label><label className="block text-sm font-semibold">Identifiant du chat<input className="mt-1 w-full rounded-xl border-slate-300" value={form.data.chat_id} onChange={e=>form.setData('chat_id',e.target.value)} placeholder="123456789"/></label><label className="block text-sm font-semibold">Nom Telegram <span className="font-normal text-slate-400">(facultatif)</span><input className="mt-1 w-full rounded-xl border-slate-300" value={form.data.telegram_username} onChange={e=>form.setData('telegram_username',e.target.value)} placeholder="@franck"/></label><InputError message={form.errors.bot_token||form.errors.chat_id}/><button disabled={form.processing} className="w-full rounded-xl bg-[#6d4cc7] px-4 py-3 font-semibold text-white">Enregistrer la connexion</button></form>
                    {connection&&<div className="mt-5 space-y-3 border-t border-[#eeeaf3] pt-5"><button onClick={()=>router.post(route('telegram.activate'))} className="w-full rounded-xl bg-[#302b45] px-4 py-3 font-semibold text-white">{connection.verified_at?'Réactiver le webhook':'Activer le bot Telegram'}</button><div className="rounded-2xl bg-[#f6f4fb] p-4 text-sm"><p className="font-semibold">Ce que Nikolaii envoie</p><label className="mt-3 flex items-center gap-3"><input type="checkbox" checked={preferences.data.decision_alerts} onChange={e=>preferences.setData('decision_alerts',e.target.checked)}/> Alertes selon mes dépenses</label><label className="mt-3 flex items-center gap-3"><input type="checkbox" checked={preferences.data.daily_summary} onChange={e=>preferences.setData('daily_summary',e.target.checked)}/> Point quotidien à 7 h 30</label><button onClick={()=>preferences.patch(route('telegram.preferences'),{preserveScroll:true})} className="mt-4 font-semibold text-[#6d4cc7]">Enregistrer les préférences</button></div><button onClick={()=>confirm('Déconnecter ce bot ?')&&router.delete(route('telegram.destroy'))} className="w-full py-2 text-sm font-semibold text-rose-600">Déconnecter le bot</button></div>}
                </section>

                <section className="mm-card min-h-[360px] p-6"><div className="flex items-start justify-between gap-4"><div><p className="mm-eyebrow">Alertes et conversations</p><h2 className="mt-1 text-xl font-semibold">Centre d’activité</h2></div><span className="rounded-full bg-[#f3f0f8] px-3 py-1 text-xs font-semibold text-[#6d4cc7]">{messages.length} récent(s)</span></div>
                    <div className="mt-5 max-h-[520px] space-y-3 overflow-y-auto pr-1">{messages.length?messages.map(message=><article key={message.id} className={`rounded-2xl border p-4 ${message.kind==='behavior_alert'?'border-amber-200 bg-amber-50':message.direction==='incoming'?'border-[#d9cef2] bg-[#f3f0f8]':'border-[#eeeaf3] bg-white'}`}><div className="flex items-center justify-between gap-3"><span className={`text-[11px] font-bold uppercase tracking-wider ${message.kind==='behavior_alert'?'text-amber-700':'text-[#8b73c8]'}`}>{message.kind==='behavior_alert'?'⚡ ':message.direction==='incoming'?'↗ ': '● '}{kindLabel[message.kind]||'Telegram'}</span><time className="text-[11px] text-[#9a96a7]">{message.sent_at?new Date(message.sent_at).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'}):''}</time></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#4f4a60]">{message.text||'Message sans texte'}</p>{message.imported&&<span className="mt-2 inline-block text-[11px] text-[#9a96a7]">Importé de Mark3</span>}</article>):<div className="flex min-h-[260px] flex-col items-center justify-center rounded-2xl border border-dashed border-[#ddd7e8] bg-[#faf9fc] p-8 text-center"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#eee9f8] text-xl">🔔</div><h3 className="mt-4 font-semibold text-[#302b45]">Nikolaii est prêt</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#8b8699]">Les alertes de rythme, achats impulsifs, grosses dépenses et dépassements de cycle apparaîtront ici après l’activation du bot.</p></div>}</div>
                    <div className="mt-5 flex flex-wrap gap-2 border-t border-[#eeeaf3] pt-4 text-xs text-[#746f86]"><span className="rounded-full bg-[#f6f4fb] px-3 py-1.5">/depense 2500 Déjeuner</span><span className="rounded-full bg-[#f6f4fb] px-3 py-1.5">/solde</span><span className="rounded-full bg-[#f6f4fb] px-3 py-1.5">/projet Sortie</span><span className="rounded-full bg-[#f6f4fb] px-3 py-1.5">/aide</span></div>
                </section>
            </div>
        </main>
    </AuthenticatedLayout>;
}
